### ISSUE TITLE
Invalid Credentials

### ISSUE THREAD

**Issue by simondeeley** [Jayfrown/symfony-ldap-example#1]
Having used your code as a template to authenticate against an LDAP server I am having trouble getting Symfony to actually return valid credentials.

I have peeled everything back to the bare-bones minimum config as per your repo yet no matter how I configure the security component it always returns a `401: Invalid Credentials` error.

Any ideas what may be going wrong?

**Comment by Jayfrown** [comment]
Hey. Without seeing your configuration I can't really do more than guess. If you can can share some more details maybe I can be more helpful. I do have some general advice.

Note that any version prior to `6.1` will treat the following scenarios as "invalid credentials":

- When the presented user credentials are incorrect (of course)
- When the configured search credentials are incorrect
- When Symfony cannot connect to the LDAP server

There's some things you could check outside of Symfony first:

- Can you connect to the LDAP server from your app host?

```
❯ nc -vz localhost 389
localhost [127.0.0.1] 389 (ldap) open
```

- Can you bind to LDAP using the configured search credentials? ([`LDAP_SEARCH_DN` and `LDAP_SEARCH_PASSWORD` in `.env`](https://github.com/Jayfrown/symfony-ldap-example/blob/master/.env#L51-L52))

```
❯ ldapwhoami -x -h localhost -p 389 -D 'cn=admin,dc=example,dc=org' -w admin
dn:cn=admin,dc=example,dc=org
```

- Does a `ldapsearch` using the configured search credentials find users in your [`LDAP_BASE_DN`](https://github.com/Jayfrown/symfony-ldap-example/blob/master/.env#L53)?

```
❯ ldapsearch -x -LLL -h localhost -p 389 -D 'cn=admin,dc=example,dc=org' -b ou=Users,dc=example,dc=org -w admin '(&(objectClass=inetOrgPerson))'
dn: uid=testuser,ou=Users,dc=example,dc=org
```

- Can you bind to LDAP using those user's credentials?

```
❯ ldapwhoami -x -h localhost -p 389 -D 'uid=testuser,ou=Users,dc=example,dc=org' -w testuser
dn:uid=testuser,ou=Users,dc=example,dc=org
```

If all of that works, check your configuration. The important bits are:

- [`services.yaml`](https://github.com/Jayfrown/symfony-ldap-example/blob/master/config/services.yaml#L25-L35) which references the LDAP host and port as defined in [`.env`](https://github.com/Jayfrown/symfony-ldap-example/blob/master/.env#L48-L50)

- The [provider in `security.yaml`](https://github.com/Jayfrown/symfony-ldap-example/blob/master/config/packages/security.yaml#L9-L16) which references the service defined above, as well as the LDAP search credentials and the `base_dn` as defined in [`.env`](https://github.com/Jayfrown/symfony-ldap-example/blob/master/.env#L51-L53)

- The [authenticator on your firewall](https://github.com/Jayfrown/symfony-ldap-example/blob/master/config/packages/security.yaml#L24-L28), which references the service defined above and sets the `dn_string`. Note that the `dn_string` must completely match your LDAP user's DN.

For example, in this repo, the `dn_string` is defined as `uid={username},%env(resolve:LDAP_BASE_DN)%` and `LDAP_BASE_DN` is defined as `ou=Users,dc=example,dc=org`, which means the `dn_string` resolves to `uid={username},ou=Users,dc=example,dc=org`. The `{username}` part is interpolated at runtime using the username provided during authentication, which means authenticating as `testuser` will match the `uid=testuser,ou=Users,dc=example,dc=org` found in the `ldapsearch` above.

**Comment by simondeeley** [comment]
Thanks for such a comprehensive reply 👍🏻

This is the first time I've needed to develop with an LDAP server so your command line tools really helped.  Thanks!  

This issue was one of those cases of a simple user-error causing me the headache.  I had a bit of lightbulb moment after I ran your above command line snippets and they all returned the expected results... 💡

Turns out I hadn't considered I was running all my services containerised (e.g. caddy web server, PHP, etc...).  I had forgot that I needed to consider how the containers talked to each other.

```LDAP_HOST="localhost"``` in .env needed to be ```LDAP_HOST="openldap"``` for Symfony to communicate with the ldap server 🤦

So... my bad but thanks for the insights to help me diagnose the issue!

**Comment by Jayfrown** [comment]
Glad I could help :)

FWIW, since I prefer having a working local environment, I use port-forwarding in my docker-compose config to expose the LDAP port to localhost as well, so I use `LDAP_HOST="localhost"` in `.env` and override it to `LDAP_HOST: openldap` in the dockerized PHP service's environment.

`.env`:
```
LDAP_HOST="localhost"
LDAP_PORT="389"
```

`docker-compose.yaml`:
```yaml
version: "3.4"

services:
  php:
  [..]
    environment:
      LDAP_HOST: openldap
      LDAP_PORT: 389

  openldap:
    image: osixia/openldap:1.5.0
    [..]
    ports:
      - "389:389"
      - "636:636"
```

Pretty much the same deal for my database string as well, `docker-compose` exposes the `database` service's port to localhost, `.env` refers to `localhost` and the docker PHP service's environment overrides this to point to the `database` service.

This way I can just run commands on my local machine instead of having to enter into the PHP container for everything.
